### ISSUE TITLE
Do not see pictures of wallabag buttons and text style is still messed up

### ISSUE THREAD

**Issue by garret** [RrOoSsSsOo/docker-wallabag-proxy#1]
Hi, I am coming from https://github.com/wallabag/docker/issues/271#issuecomment-1010237760 
I am using wallabag via docker on my raspberry pi 4. I set it up the `SYMFONY__ENV__DOMAIN_NAME` as my vpn address and it works. However, when I try to access from my local ip address I can only see texts and images of the articles but all the images of wallabag buttons are missing and, additionally, I can see that the text is bigger, so like the style is a bit messed up. In particular, this is what I see by accessing wallabag from my local ip address: 

![image](https://user-images.githubusercontent.com/27555/149022524-dc9188ab-1897-48ec-8e12-02441f261254.png)

I tried your solution but still have the same issue. Do you know if it can be solved? 

This is my docker-compose which includes your modification: 

```
    wallabag:
        build: https://github.com/wallabag/docker.git#2.4.2
        ports:
            - 1234:80
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TIMEZONE}
            - SYMFONY__ENV__DOMAIN_NAME="http://11.12.13.14:1234"
            - SYMFONY__ENV__REDIS_HOST=wallabag-redis
            - SYMFONY__ENV__REDIS_PORT=6385
        volumes:
            - ${CONFIG_FOLDER}/wallabag/images:/var/www/wallabag/web/assets/images
            - ${CONFIG_FOLDER}/wallabag/data:/var/www/wallabag/data
            - ${CONFIG_FOLDER}/wallabag/AppKernel.php:/var/www/wallabag/app/AppKernel.php
        healthcheck:
            test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
            interval: 1m
            timeout: 3s
        depends_on:
            - wallabag-redis
        labels:
            - com.centurylinklabs.watchtower.enable=false
        container_name: wallabag
        restart: unless-stopped
        image: wallabag:2.4.2
```
